FROM node:18-bookworm
LABEL MAINTAINER="MiaoWoo(admin@yumc.pw)"

ENV DEBIAN_FRONTEND=noninteractive \
    # Java debian default install at /usr/lib/jvm/default-jvm
    JAVA_HOME=/usr/lib/jvm/default-java \
    # Golang debian default install at /usr/lib/go
    GOROOT=/usr/lib/go \
    SHELL=/bin/zsh \
    PHP_VERSION=8.2

RUN apt-get update && \
    apt-get install -y \
    # Base Package
    git zsh tmux nano bash tzdata openssl curl inotify-tools \
    # Go
    golang musl-dev \
    # Java
    maven gradle \
    # Python
    python3 python3-dev python3-pip python3-full \
    # PHP
    php && \
    rm -rf /var/lib/apt/lists/* && \
    # link python exec to python3
    ln -sf /usr/bin/python3 /usr/bin/python && \
    # link php exec to php${PHP_VERSION}
    # ln -sf /usr/bin/php${PHP_VERSION} /usr/bin/php && \
    corepack enable && \
    corepack prepare pnpm@latest --activate

# Rust
RUN bash -c "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y -v \
    && source $HOME/.cargo/env \
    && rustup default stable"

# Python
RUN pip install --break-system-packages python-language-server autopep8 pylint

# PHP
RUN curl -s -o composer-setup.php https://getcomposer.org/installer \
    && php composer-setup.php --dev --install-dir=/usr/bin --filename=composer \
    && rm composer-setup.php \
    # PHP-CS-Fixer
    && mkdir -p /usr/local/php-cs-fixer \
    && composer require --working-dir=/usr/local/php-cs-fixer friendsofphp/php-cs-fixer \
    && ln -sf /usr/local/php-cs-fixer/vendor/bin/php-cs-fixer /usr/bin/php-cs-fixer

# Install Tmux Config & On-My-ZSH
RUN set -ex && \
    mkdir ~/.tmux && \
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && \
    wget -qO- https://raw.githubusercontent.com/502647092/Dockerfile/master/development/tmux.conf > ~/.tmux.conf && \
    ~/.tmux/plugins/tpm/bin/install_plugins && \
    git clone --depth=1 https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh && \
    cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc && \
    sed -i s@ZSH_THEME=\"robbyrussell\"@ZSH_THEME=\"ys\"@g ~/.zshrc && \
    echo 'alias tmux="tmux -u"' >> ~/.zshrc && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone
