FROM alpine
LABEL MAINTAINER="MiaoWoo(admin@yumc.pw)"

# Java alpine default install at /usr/lib/jvm/default-jvm
ENV JAVA_HOME=/usr/lib/jvm/default-jvm \
    # Golang alpine default install at /usr/lib/go
    GOROOT=/usr/lib/go \
    GOPATH=/home/theia/go \
    PATH=$PATH:${GOROOT}/bin:${GOPATH}/bin \
    SHELL=/bin/zsh

##GO
#Required to use go get with git source
RUN apk add --no-cache \
    # Base Package
    git ttf-freefont tzdata ca-certificates \
    zsh tmux nano bash tzdata openssh openssl curl inotify-tools \
    # Build tools
    make g++ libx11-dev libxkbfile-dev libsecret libsecret-dev \
    # Theia NodeJS
    nodejs yarn npm \
    # Go
    go musl-dev \
    # Java
    openjdk11 maven gradle \
    # Python
    python3 python3-dev py3-pip \
    # PHP \
    php php7-xml php7-zip php7-dom \
    php-json php-phar php7-zlib php7-curl \
    php7-gd php7-ctype php-iconv php-openssl php-mbstring \
    php7-fileinfo php7-simplexml php7-xmlwriter php7-xmlreader php7-tokenizer && \
    # link python exec to python3
    ln -sf /usr/bin/python3 /usr/bin/python

# Python
RUN pip install python-language-server autopep8 pylint

# PHP
RUN curl -s -o composer-setup.php https://getcomposer.org/installer \
    && php composer-setup.php --install-dir=/usr/bin --filename=composer \
    && rm composer-setup.php

# Install Tmux Config & On-My-ZSH
RUN set -ex && \
    mkdir ~/.tmux && \
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && \
    wget -qO- https://raw.githubusercontent.com/502647092/Dockerfile/master/development/tmux.conf > ~/.tmux.conf && \
    ~/.tmux/plugins/tpm/bin/install_plugins && \
    git clone --depth=1 git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh && \
    cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc && \
    sed -i s@ZSH_THEME=\"robbyrussell\"@ZSH_THEME=\"ys\"@g ~/.zshrc && \
    echo 'alias tmux="tmux -u"' >> ~/.zshrc && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone
