FROM node:8.16.0-alpine
LABEL container="MiaoWoo(admin@yumc.pw)"

RUN set -ex &&\
    apk --no-cache add curl \
    && echo "Pulling watchdog binary from Github." \
    && curl -sSL https://github.com/openfaas-incubator/of-watchdog/releases/download/$(curl -sI https://github.com/openfaas-incubator/of-watchdog/releases/latest | grep Location | awk -F"/" '{ printf "%s", $NF }' | tr -d '\r')/of-watchdog > /usr/bin/fwatchdog \
    && chmod +x /usr/bin/fwatchdog \
    && apk del curl \
    && rm -rf /var/cache/apk/*
