FROM miaowoo/node-tini:8.15.0-alpine
LABEL maintainer="admin@yumc.pw(MiaoWoo)"

RUN set -x && \
  echo "http://mirrors.aliyun.com/alpine/latest-stable/main/" > /etc/apk/repositories && \
  apk add --no-cache python tzdata && \
  cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
  rm -rf /var/cache/apk/* && \
  echo "Asia/Shanghai" > /etc/timezone && \
  wget https://git.yumc.pw/502647092/tera/archive/master.tar.gz && \
  tar -xvzf master.tar.gz && \
  rm -rf master.tar.gz && \
  mv tera/ /app/

WORKDIR /app/Source
RUN  yarn config set registry https://repo.yumc.pw/repository/npm-taobao && yarn

ENV PORT 80
ENV PASSWD 123456
EXPOSE 80

CMD node set httpport:${PORT} password:${PASSWD} && node run-node.js
